max_results: 2
max_search_result_pages: 2

domain:
    - "amazon.com"

save_images: False
save_description_images: False
save_full_page_images: False
export_reviews:
    - "positive"
    - "critical"
    - "3_star"
log_levels:
    - "info"
    - "debug"